# type Query {

# }

# type Mutation {
  
# }

type Example {
  foo: String!
}

enum Selection {
  Rock
  Paper
  Scissors
}


type Result @embedded {
  selection: Selection!
  opponentSelection: Selection!
  message: String!
}

type Query {
  play(selection: Selection!): Result! @resolver(name: "play")
}
